/**
 * Create Server Audit Script Tool — Cloudstick API + SSH fallback
 *
 * Creates a standardized server audit script at /usr/local/bin/server-audit.sh
 * using the Cloudstick upload_file API, then sets +x permissions via SSH.
 * This is a Tier 3 tool (HITL required).
 */

import { getCloudstickClient } from '../../api/cloudstick_client.js';
import { getCloudstickUser } from '../../api/cloudstick_context.js';
import { env } from '../../config/env.js';
import { sshExec } from '../../utils/ssh.js';
import { resolveServerArg } from '../../utils/server_registry.js';
import { encodeToolApprovalCommand } from '../../hitl/tool_approval.js';
import type { Tool } from '../types.js';

const userId = () => getCloudstickUser()?.cloudstick_user_id
    ?? env.CLOUDSTICK_USER_ID
    ?? (() => { throw new Error('CLOUDSTICK_USER_ID is not set'); })();

// Standard server audit script content
const AUDIT_SCRIPT_CONTENT = `#!/bin/bash
# Server Audit Script — generated by CloudClaw
# Runs daily via cron at 10 AM

LOG_DIR="/var/log/cloudclaw-audit"
mkdir -p "$LOG_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="$LOG_DIR/audit_$TIMESTAMP.log"

{
    echo "=== Server Audit Started: $(date) ==="
    echo "Hostname: $(hostname)"
    echo "Uptime: $(uptime)"
    echo ""
    echo "=== Disk Usage ==="
    df -h | grep -v tmpfs
    echo ""
    echo "=== Memory Usage ==="
    free -h
    echo ""
    echo "=== Top CPU Processes ==="
    ps aux --sort=-%cpu | head -10
    echo ""
    echo "=== Top Memory Processes ==="
    ps aux --sort=-%mem | head -10
    echo ""
    echo "=== Service Status ==="
    for svc in nginx php-fpm mysql mariadb postgresql; do
        if systemctl is-active --quiet $svc 2>/dev/null; then
            echo "$svc: RUNNING"
        else
            echo "$svc: STOPPED or NOT INSTALLED"
        fi
    done
    echo ""
    echo "=== Recent Errors (last 50 lines) ==="
    journalctl -p err --since "1 day ago" --no-pager -n 50 2>/dev/null || echo "No error logs found"
    echo ""
    echo "=== SSL Certificates Expiring in 30 days ==="
    find /etc/letsencrypt/live -name "cert.pem" -exec openssl x509 -in {} -noout -dates 2>/dev/null \\; | grep -B1 "notAfter" | grep "notAfter" | while read line; do
        echo "$line"
    done
    echo ""
    echo "=== Server Audit Completed: $(date) ==="
} | tee "$LOG_FILE"

# Keep only last 30 days of logs
find "$LOG_DIR" -name "audit_*.log" -mtime +30 -delete 2>/dev/null
`;

const AUDIT_SCRIPT_PATH = '/usr/local/bin/server-audit.sh';

const createServerAuditScriptTool: Tool = {
    name: 'create_server_audit_script',
    description:
        'Create a standardized server audit script at /usr/local/bin/server-audit.sh on a Cloudstick server. ' +
        'The script collects disk, memory, CPU, service status, error logs, and SSL certificate info daily. ' +
        'Uploads the script via Cloudstick API then sets +x via SSH. Requires HITL approval.',
    parameters: {
        type: 'object',
        properties: {
            server_id: { type: 'string', description: 'Cloudstick server ID' },
            server_label: { type: 'string', description: 'Human-readable server label' },
            script_path: {
                type: 'string',
                description: 'Path where to create the script (default: /usr/local/bin/server-audit.sh)',
            },
        },
        required: ['server_id', 'server_label'],
    },
    approvalTier: 3,
    getRationale: (args) =>
        `This will create the audit script at ${args.script_path ?? AUDIT_SCRIPT_PATH} on server ${args.server_label ?? args.server_id} and set it as executable.`,
    getApprovalRequest: (args) => ({
        command: encodeToolApprovalCommand('create_server_audit_script', {
            server_id: String(args.server_id),
            server_label: String(args.server_label),
            script_path: String(args.script_path ?? AUDIT_SCRIPT_PATH),
        }),
        targetHost: String(args.server_label ?? args.server_id ?? 'unknown'),
        rationale: `Create server audit script at ${args.script_path ?? AUDIT_SCRIPT_PATH} and set it executable (+x).`,
    }),
    execute: async (args) => {
        const serverId = String(args.server_id);
        const serverLabel = String(args.server_label ?? args.server_id);
        const scriptPath = String(args.script_path ?? AUDIT_SCRIPT_PATH);
        const fileName = scriptPath.split('/').pop() ?? 'server-audit.sh';
        const destinationPath = scriptPath.replace(/\/[^\/]+$/, ''); // parent dir

        try {
            // Step 1: Resolve server to get SSH details
            const server = await resolveServerArg({ server_label: serverLabel, server_id: serverId });

            // Step 2: Upload script via Cloudstick API (base64 encoded)
            const client = getCloudstickClient();
            const base64Content = Buffer.from(AUDIT_SCRIPT_CONTENT, 'utf8').toString('base64');
            const uploadResult = await client.uploadFile(serverId, userId(), {
                destination_path: destinationPath,
                file_content: base64Content,
                file_name: fileName,
            });

            // Step 3: Set +x via SSH
            const chmodResult = await sshExec(server.ip, `chmod +x ${scriptPath}`, {
                user: server.sshUser,
                port: server.sshPort,
            });

            return {
                success: true,
                output: `Server audit script created at ${scriptPath} and set executable.\n` +
                    `Upload result: ${JSON.stringify(uploadResult)}\n` +
                    `Permissions: ${chmodResult}`,
            };
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return {
                success: false,
                output: `Failed to create server audit script: ${msg}`,
            };
        }
    },
};

export { createServerAuditScriptTool };
